Repository natcap/pygeoprocessing, pull requests merged in 2021-05, with the labels that each got.

#187 fixes #177 raises an exception if transform goes out of bounds
  HISTORY.rst
  src/pygeoprocessing/geoprocessing.py
  tests/test_geoprocessing.py
Labels: bug

#186 fixes #180 convolve_2d hangs on integer kernel
  HISTORY.rst
  src/pygeoprocessing/geoprocessing.py
  tests/test_geoprocessing.py
Labels: bug

#189 fixes #161 extra long runtimes on large subwatersheds with large coordinates
  src/pygeoprocessing/routing/routing.pyx
Labels: bug

#188 fixes #168, valueerror if non-square blocksize on convolve 2d
  HISTORY.rst
  src/pygeoprocessing/geoprocessing.py
  tests/test_geoprocessing.py
Labels: bug

#185 Bugfix/dist to channel no channels 171
  HISTORY.rst
  src/pygeoprocessing/routing/routing.pyx
  tests/test_routing.py
Labels: bug

#178 add to convolve_2d docstring
  src/pygeoprocessing/geoprocessing.py
Labels: documentation

#193 fixes #192, change to long, better logging, updated history
  HISTORY.rst
  src/pygeoprocessing/geoprocessing_core.pyx
Labels: bug

#195 Release/2.2.0
  HISTORY.rst
Labels: task

#200 Bugfix/revert to geom bounds
  HISTORY.rst
  src/pygeoprocessing/geoprocessing.py
Labels: bug

#191 Feature/force single drainage point 190
  HISTORY.rst
  src/pygeoprocessing/routing/__init__.py
  src/pygeoprocessing/routing/routing.pyx
  tests/test_geoprocessing.py
  tests/test_routing.py
Labels: bug, enhancement
